name: Build Android Kernel (All Devices)

on:
  push:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  pull_request:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if exynos9830_defconfig is not modified (manual trigger)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools ccache

      - name: Build Kernel
        run: |
          chmod +x ./build_all.sh
          ./build_all.sh

      - name: Find built zip in root directory
        id: find_zip
        run: |
          ZIP_FILE=$(find . -type f -name "*.zip" | head -n 1)
          if [[ -z "$ZIP_FILE" ]]; then
            echo "No ZIP found! Exiting."
            exit 1
          fi
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV

      - name: Upload built kernel
        uses: actions/upload-artifact@v4
        with:
          name: built-kernel
          path: ${{ env.ZIP_FILE }}
