name: Build Android Kernel (Single Build)

on:
  push:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  pull_request:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if exynos9830_defconfig is not modified (for manual trigger)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools ccache

      - name: Build Kernel
        run: |
          chmod +x ./build_all.sh
          ./build_all.sh

      - name: Find Flashable Zip
        id: find_zip
        run: |
          echo "ZIP_PATH=$(find build/out/all/ -type f -name 'ArtisanKRNL_*.zip')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kernel-build
          path: ${{ env.ZIP_PATH }}
