name: Build Android Kernel

on:
  push:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  pull_request:
    branches: [ main ]
    paths:
      - 'arch/arm64/configs/exynos9830_defconfig'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if exynos9830_defconfig is not modified (manual trigger)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache bc bison flex libssl-dev libelf-dev

      - name: Build kernel
        run: |
          chmod +x ./build_all.sh
          ./build_all.sh

      - name: Find built zip
        id: find_zip
        run: |
          ZIP_FILE=$(find build/out/all/ -type f -name "ArtisanKRNL_*.zip" | head -n 1)
          echo "zip_file=$ZIP_FILE" >> "$GITHUB_ENV"
          echo "Found zip: $ZIP_FILE"

      - name: Upload built kernel
        uses: actions/upload-artifact@v4
        with:
          name: built-kernel
          path: ${{ env.zip_file }}
